### ISSUE TITLE
Couple errors on unity Asset package with .NET 4.x

### ISSUE THREAD

**Issue by marchys** [Arvtesh/UnityFx.Async#1]
It seems that in the Unity Asset the file _UnityExtensions.cs_ line 124 variable should be _op instead of op.
And in the _LoadTextureHelper.UseCases.Await.cs_ it's crashing because it seems _LoadTextureAsync_ needs a GetAwaiter?

**Comment by abogarsukov** [comment]
Thank you for the notice. I'll look into it and publish the updated asset store package. Could you tell me what Unity version do you use?

**Comment by marchys** [comment]
2018.1

**Comment by Arvtesh** [comment]
Should be fixed now. The NuGet and releases are updated. The asset store package will be available as soon as Unity approves it. Thanks for raising this!
