### ISSUE TITLE
How to chain calls

### ISSUE THREAD

**Issue by imtrobin** [Arvtesh/UnityFx.Async#2]
Hi, I'm trying to chain multiple GET calls, I'm not sure how should it be done correctly (Unity 5.6.6)

```
        var downloadOps = DownloadTextAsync ("http://www.google.com")
            .Then (text => Debug.Log (text))

          // this does not catch error
          .ContinueWith (op => DownloadTextAsync ("http://www.thisdoesnotexistxxcaas.com").Then (text => Debug.Log (text)))
  
           // Then doesn't wait
            .ContinueWith (op => DownloadTextAsync ("http://www.thisdoesnotexistxxcaas.com"), AsyncContinuationOptions.ExecuteSynchronously)
            .Then (text => Debug.Log (text))

           .Catch (e => Debug.LogException (e));
```

**Comment by Arvtesh** [comment]
Hi, @imtrobin. The intended way of doing what you need is something like this:
```csharp
var downloadOps = AsyncWww.GetText("http://www.google.com")
	.Then(text => Debug.Log(text))
	.Then(() => AsyncWww.GetText("http://www.thisdoesnotexistxxcaas.com")
	.Then(text => Debug.Log(text)))
	.Then(() => AsyncWww.GetText("http://www.thisdoesnotexistxxcaas.com"))
	.Then(text => Debug.Log(text))
	.Catch(e => Debug.LogException(e));
````
Please note that github issues is not the right place to ask questions. There is a dedicated forum thread for this library: [Unity forums link](https://forum.unity.com/threads/asynchronous-operations-promises-for-unity-free.522989/).

**Comment by imtrobin** [comment]
Thanks, noted. Here's a bug, but I think it's Unity 5.6.6 rather than yours. The AsyncWww.GetText is using UnityWebRequest.Get , which .text returns empty even if successful. I've verified this in seperate project and have reported this to Unity
